# Generated by Django 4.1.7 on 2023-03-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100)),
                ('pgRating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('recommended', models.CharField(choices=[('Y', 'Positive Review'), ('N', 'Negative Review')], max_length=1)),
                ('movie_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_gross', models.IntegerField()),
                ('distributor', models.CharField(max_length=100)),
                ('movie_referenced', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxOffice', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('day_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('movie_appearances', models.ManyToManyField(related_name='moviesAndActors', to='api.movie')),
            ],
        ),
    ]
