# Generated by Django 4.1.7 on 2023-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
