# Generated by Django 4.1.7 on 2023-03-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_rating_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxoffice',
            name='movie_referenced',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boxOffice', to='api.movie'),
        ),
    ]
