# Generated by Django 4.1.7 on 2023-03-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_boxoffice_movie_referenced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
