# Generated by Django 4.1.7 on 2023-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
