# Generated by Django 4.1.7 on 2023-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_in_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
