# Generated by Django 4.1.7 on 2023-03-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_movie_language_movie_duration_in_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxoffice',
            old_name='lifetime_gross',
            new_name='lifetime_gross_in_millions',
        ),
    ]
