# Generated by Django 4.1.7 on 2023-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_lifetime_gross_boxoffice_lifetime_gross_in_millions'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxoffice',
            name='budget_in_millions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
