# Generated by Django 4.1.7 on 2023-03-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie_appearances',
        ),
        migrations.CreateModel(
            name='MoviesAndActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_filmed', models.IntegerField()),
                ('director_notes', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
        ),
    ]
